import type { Metadata } from "next";
import "bootstrap-icons/font/bootstrap-icons.css";
import { Raleway, Didact_Gothic } from "next/font/google";
import "./globals.css";
import { NextFontWithVariable } from "next/dist/compiled/@next/font";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const raleway: NextFontWithVariable = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
});

const didactGothic: NextFontWithVariable = Didact_Gothic({
  variable: "--font-didact-gothic",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Navbar />
      <body className={``}>{children}</body>
      <Footer />
    </html>
  );
}
