import type { Metadata } from "next";
import "bootstrap-icons/font/bootstrap-icons.css";
import { Raleway } from "next/font/google";
import "./globals.css";
import { NextFontWithVariable } from "next/dist/compiled/@next/font";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const raleway: NextFontWithVariable = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Nestegg",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
